### PR TITLE
Fix issues related to the Authorization & exceptions handling

### LINKED ISSUE #45: Handle errors when UI can't reach the backend

### PR DESCRIPTION
**Pull request by Bardin08**
In this PR, I added `UserSecrets` for the Identity Service and resolved a bunch of issues related to the identity. Also shared exceptions handler is used now.

Replace exception filter with exceptions middleware to follow recommended approaches: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/handle-errors?view=aspnetcore-7.0#exceptions

Closes #45 #77

### CODE REVIEW

**Comment by YaroslavKSE** [comment]
> Replace exception filter with exceptions middleware to follow recommended approaches: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/handle-errors?view=aspnetcore-7.0#exceptions


Am I correct that now we don't need custom Exception filter and just use standart from the link porvided above?

**Review by YaroslavKSE — APPROVED** [review]
Nice changes! Approve!

**Comment by Bardin08** [comment]
@YaroslavKSE
Yes you're right, we don't need Filter, but we still have to use Middleware. This is caused by limited filters support by Minimal APIs

**Review by roflmyrlok — APPROVED** [review]
LGTM

**Pull request merged**
