### PR TITLE
Fixed migrations by adding DesignTimeDbContextFactory

### LINKED ISSUE #171: fix migrations

### PR DESCRIPTION
**Pull request by YaroslavKSE**
Closes #171 
**Here is the results:**
```shell
PS D:\C#\AcademicHub\Identity\Identity.Data> dotnet ef migrations add Test                        
Build started...
Build succeeded.
Done. To undo this action, use 'ef migrations remove'

``` 

**Here is logs from docker:**
image

@Bardin08 For some reason I can't commit migrations. However, they are created. Here is the screenshot:
image

@Bardin08  By the way, you can't undo migrations by running the command dotnet ef migrations remove. This is because the postgres sql is running inside docker container and have no port for outside world. Should we then delete them manually?

### CODE REVIEW

**Comment by Bardin08** [comment]
1. I don't understand which issue u have with committing them.
2. Yep, it's okay to drop them manually

**Review by Bardin08 — APPROVED** [review]

**Comment by Bardin08** [comment]
looks like this is a duplicate for #171

**Comment by YaroslavKSE** [comment]
> 1. I don't understand which issue u have with committing them.
> 2. Yep, it's okay to drop them manually

1. I'll check one more time maybe it is the problem of gitignore 
2. Thanks, so we will uses this approach
3. I'll add factories for anouther services and commit changes tomorrow

**Comment by Bardin08** [comment]
@YaroslavKSE Okay! That look good. Let's move forward with this approach

**Comment by Bardin08** [comment]
@YaroslavKSE do u have any plans to merge this PR?

**Comment by Bardin08** [comment]
I'm jumping out at this point, and yeah, if u or someone else from the team needs my help, just let me know on Slack or Telegram, and I'll do my best to assist!

**Pull request merged**
