### PR TITLE
Branch protectoion: Meseare code coverege

### LINKED ISSUE #56: Measure Code Coverage on PRs and make it impossible to complete PR
- without 100% coverage of BLL
 - without 60% coverage of PL

### PR DESCRIPTION
**Pull request by Zakhar-Khmurych**
Closes #56

### CODE REVIEW

**Comment by YaroslavKSE** [comment]
Zakhar, I can't see the percantage of coverage in the workflows. Can you print the value during workflow executions?

**Review by YaroslavKSE — CHANGES_REQUESTED** [review]
Need to fix code coverege, as there is no " No coverage data found." exception
https://github.com/AcademicHubOrg/AcademicHub/pull/101/checks#step:6:77

**Comment by Bardin08** [comment]
@Zakhar-Khmurych moved to milestone 3

**Review by qualia4 — APPROVED** [review]
its ok

**Pull request merged**
